#!/bin/sh

unset BIN_DIR
unset DATA_DIR
unset EFIT_TABLE_DIR
unset EFIT_INPUT_DIR
unset WGEQDSK_BIN_DIR
unset WGEQDSK_BIN_NAME
unset FASTRAN_BIN_DIR
unset FASTRAN_BIN_NAME
unset FASTRAN_SERIAL_BIN_NAME
unset EFIT_BIN_DIR
unset EFIT_BIN_NAME
unset ESC_BIN_DIR
unset ESC_BIN_NAME
unset NUBEAM_BIN_DIR
unset NUBEAM_BIN_NAME
unset TORAY_BIN_DIR
unset TORAY_BIN_NAME
unset CURRAY_BIN_DIR
unset CURRAY_BIN_NAME
unset GENRAY_BIN_DIR
unset GENRAY_BIN_NAME
unset NFREYA_BIN_PATH
unset NFREYA_BIN_NAME
unset NFREYA_DATA_ROOT
unset PSTOOL
unset PS_BACKEND
