#!/bin/bash
#SBATCH -p debug
#SBATCH --nodes=2
#SBATCH -t 00:10:00
#SBATCH -C haswell

#SBATCH -J ips_fastran
#SBATCH -e ips.err
#SBATCH -o ips.out

module load python
module load gcc
module load intel
source activate /global/common/software/atom/cori/cesol_conda/v0.1

export PATH=/global/homes/r/rwp/.local/cori/3.9-anaconda-2021.11/bin:$PATH

ips.py --config=ips_massive_parallel.config --platform=cori_haswell.conf --log=ips.log
