#!/bin/bash

#SBATCH --image=docker:registry.services.nersc.gov/rwp53/ips-massive-serial:dev
#SBATCH --volume="/global/cscratch1/sd/rwp/tmpfiles:/tmp:perNodeCache=size=1G"

#SBATCH -p debug
#SBATCH --nodes=1
#SBATCH -t 00:10:00
#SBATCH -C haswell

#SBATCH -J ips_fastran
#SBATCH -e ips.err
#SBATCH -o ips.out

#module load python/3.8-anaconda-2020.11
module load python
conda activate massiveparallel

ips.py --config=ips_massive_parallel_shifter.config --platform=cori_haswell.conf --log=ips.log
