#!/usr/bin/env python

"""
 ------------------------------------------------------------------------------
  metric from efit
  JM
 ------------------------------------------------------------------------------
"""

import sys,os,re,pickle,glob
from numpy import *
from scipy.interpolate import interp1d
import Namelist

import zefitdata
import zfdat

def zinmetric(geq,nrho=51,iwrt=False):

    #gfile = os.path.join(efitdir,'g%06d.%05d'%(shot,time))

    #print 'efitdir = ',efitdir
    #print 'gfile   = ',gfile

    ##--------------------------------------------------------------
    ## read g/aeqdsk file
    ##

    #geq = zefitdata.efitdata(gfile,"ps",nrho=101,nrho_eq=101,nth_eq=101,nrho_eq_geo=101)

    #--------------------------------------------------------------
    # configuration
    #

    ip  = geq['cpasma']
    r0  = geq["rzero" ]
    b0  = geq["bcentr"]

    #--------------------------------------------------------------
    # setup rho grid
    #

    psi = geq["ps"]["psipol"]/geq["ps"]["psipol"][-1]  # equi-drho grid
    
    psir = (geq["ssibry"]-geq["ssimag"])*psi+geq["ssimag"] 

    nrho = len(psi)
    rho = arange(nrho)/(nrho-1.0)
    drho = 1.0/(nrho-1.0)

    rhob = (geq["ps"]["phit"][-1]/pi/abs(geq["bcentr"]))**0.5 

    rhopsi = interp1d(psi,rho,kind='cubic')

    #--------------------------------------------------------------
    # metrics
    #

    ipol = geq["ps"]["g_eq"]/(r0*b0)
    ipol = abs(ipol)
    volp = 4.0*pi*pi*rho*rhob*r0/ipol/(r0*r0*geq["ps"]["gr2i"])

    g11 = volp*geq["ps"]["grho2"]*rhob**2
    g22 = r0*volp/(4.0*pi*pi)*geq["ps"]["grho2r2i"]*rhob**2
    g33 = r0*r0*geq["ps"]["gr2i"]

    gradrho = geq["ps"]["grho1"]*rhob

    area = geq["ps"]["surf"]
    rmajor = geq["ps"]["Rmajor_mean"]
    rminor = geq["ps"]["rMinor_mean"]
    shift = rmajor-r0
    kappa = geq["ps"]["elong"]
    delta = geq["ps"]["triang"]
    pmhd = geq["ps"]["P_eq"]
    qmhd = geq["ps"]["q_eq"]

    #--------------------------------------------------------------
    # out data
    #

    metric = Namelist.Namelist()

    metric['inmetric']['Ip'     ] = [ip] 
    metric['inmetric']['bcentr' ] = [b0]
    metric['inmetric']['rmajor' ] = [r0] 
    metric['inmetric']['aminor' ] = [rminor[-1]] 
    metric['inmetric']['kappa'  ] = [kappa [-1]]
    metric['inmetric']['delta'  ] = [delta [-1]]

    metric['inmetric']['nrho'   ] = [nrho]
    metric['inmetric']['rhob'   ] = [rhob]
    metric['inmetric']['rho'    ] = rho
    metric['inmetric']['volp'   ] = volp
    metric['inmetric']['ipol'   ] = ipol 
    metric['inmetric']['g11'    ] = g11
    metric['inmetric']['g22'    ] = g22
    metric['inmetric']['g33'    ] = g33
    metric['inmetric']['gradrho'] = gradrho
    metric['inmetric']['area'   ] = area
    metric['inmetric']['a'      ] = rminor
    metric['inmetric']['rtor'   ] = rmajor
    metric['inmetric']['shift'  ] = shift
    metric['inmetric']['elong'  ] = kappa
    metric['inmetric']['triag'  ] = delta
    metric['inmetric']['pmhd'   ] = pmhd
    metric['inmetric']['qmhd'   ] = qmhd
    metric['inmetric']['er'     ] = zeros(nrho) #<======
   #metric['inmetric']['jtor'   ] = jtor

    #--------------------------------------------------------------
    # write
    #

    if iwrt=='nml':
        metric.write("inmetric.nml")

    elif iwrt=='fdat':
        f = open("inmetric","w")
        f.write(" # generated by zinmetric.py Ver+Oct2009\n")
        for p in metric['inmetric'].keys():
            if type(metric["inmetric"][p][0]) == type(1):
                zfdat.write_i(p,metric["inmetric"][p],"",f)
            else:
                zfdat.write_f(p,metric["inmetric"][p],"",f)
        f.close()

    #--------------------------------------------------------------
    # return 
    #

    return metric

###############################################################################
# check

if __name__=="__main__":

   #efitdir = '.'
   #shot = 147634
   #time = 4000
   #gfile = os.path.join(efitdir,'g%06d.%05d'%(shot,time))

   efitdir = '.'
   gfile = 'geqdsk'
   print 'efitdir = ',efitdir
   print 'gfile   = ',gfile

   geq = zefitdata.efitdata(gfile,"ps",nrho=51,nrho_eq=51,nth_eq=101,nrho_eq_geo=51)
   metric = zinmetric(geq,nrho=51,iwrt='fdat')

